baseURL = "https://arslaniqbal.com/"
languageCode = "en-us"
title = "Muhammad Arslan Iqbal"

[params]
  description = "PhD Economics Candidate at the University of Melbourne"
  author = "Muhammad Arslan Iqbal"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
  [[menu.main]]
    name = "CV"
    url = "/CV.pdf"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true